name: Build Release APK

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        run: |
          sudo apt-get update
          sudo apt-get install -y git
          git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY .
      - name: Set up JDK
        run: |
          sudo apt-get install -y openjdk-8-jdk
          export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
      - name: Make gradlew Executable
        run: chmod +x ./gradlew
      - name: Build Release APK
        run: ./gradlew assembleRelease
      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Built APK
          path: app/build/outputs/apk/release/
